### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by manask88** [jmurzy/react-router-native#1]
I think you forgot to include some files in your push.  RN complains that It cannot find the app/routes folder. I took a quick look and I couldn't even find the app folder for the example!

**Comment by jmurzy** [comment]
Thanks for the heads up. I've just open sourced the core early this morning. I'm still working on documentation and an example app. It might take a couple <s>days</s>weeks, but I'll try to get one up soon.

🍺

**Comment by jonathanglasmeyer** [comment]
I am looking for a routing lib that provides a react-router API and your approach is the only one I've found. I'd be interested in helping out. A running example would be a great start. 👍🏻:)

**Comment by jmurzy** [comment]
@jonathanewerner I'd love some help here for sure 👍— however, the reason I've not been able to publish an example is that the NavigationExperimental API is going through a [drastic](https://github.com/facebook/react-native/commit/14eb427a8061e0c904ace022535070150c6872d4) [clean](https://github.com/facebook/react-native/commit/7db7f78dc7d2b85843707f75565bcfcb538e8e51) [up](https://github.com/facebook/react-native/commit/c3714d7ed7c8ee57e005d51147820456ef8cda3e) phase that forces me to make [breaking](https://github.com/jmurzy/react-router-native/commit/5afc5a082e734a66722afd48ec7c0bf75beb24c7) [changes](https://github.com/jmurzy/react-router-native/commit/30bd11a308aaa1132f075275544399ed0002a2fe).  

Believe me I'm putting in all the extra hours I can to publish this to npm—but perhaps you're right and I should just put an example up and see how the community can help with some of this.

🍺

**Comment by jonathanglasmeyer** [comment]
Ok, good to know the background here. I'm just getting started with the react-native ecosystem, so this helps to know what you're dealing with.
Your [gif-example](https://raw.githubusercontent.com/jmurzy/react-router-native/master/docs/screenshot.gif) looks quite comprehensive. Would it make sense to have a "minimal" example to get _something_ working first? Maybe that one won't break as much? Just a thought. 
At work we have an react webapp that we want to also implement in react native (main reason: ios push notifications). We hope to be able to share the container components between web and native. These components depend on react-router and a flux implementation. If we want to go down that route it means that we need to find a react-router compatible routing lib. So i've pretty much got a full-time job's worth of time to put in to this lib if it proves viable. 
If you can provide pointers at where help is needed, i'll be happy to jump in. :+1: :)

**Comment by jmurzy** [comment]
I just added an example app to the repo—but keep in mind that everything is [still](https://github.com/jmurzy/react-router-native/issues/2) [experimental](https://github.com/jmurzy/react-router-native/issues/3). 

Also, I'm still working on the default behavior of `<StackRoute>`, especially when they are nested. So we are not quite there yet, and I think, to prevent distractions we should not publish this to npm as is.

@jonathanewerner if you are still interested in helping, going forward, I'll be documenting my progress in Github Issues. I greatly appreciate contributions and feel free to ping me on [Discord](https://discord.gg/0ZcbPKXt5bYaNQ46rl) when if you have any questions.
