### ISSUE TITLE
`history.transitionTo` is not a function when using `replace` in `onEnter` hook

### ISSUE THREAD

**Issue by jonathanglasmeyer** [jmurzy/react-router-native#12]
### Version

| Dependency | Version |
| --- | --- |
| react-router-native | 2.0.0-alpha.0 |
| react-router | 3.0.0-alpha.1 |
| react-native | 0.28.0-rc.0 |
### Expected Behavior

I want to use redirecting behaviour like so:

```
const redirect = (from_, to, query = {}) => (nextState, replace) => {
  if (nextState.location.pathname.match(from_)) {
    replace({pathname: to, query});
  }
};

export default <Route
  path='/'
  onEnter={redirect(/^\/$/, '/orders/')}
  component={AppController} />;
```

This should redirect to `/orders`/ when visiting `/`.
### Actual Behavior

Instead this fails with the following error:
<img src="https://cloud.githubusercontent.com/assets/3755413/15922519/6269b5a4-2e28-11e6-8b0f-da169e5e5fb4.png" width="280" />

When logging `history` at https://github.com/reactjs/react-router/blob/next/modules/createTransitionManager.js#L229 (this is where the error occurs) it shows that `history` has the following methods:
![screen shot 2016-06-09 at 10 06 10](https://cloud.githubusercontent.com/assets/3755413/15922809/f8348f40-2e29-11e6-8782-1b1796ce04f9.png)

I'm not sure if this is an error of react-router or the interaction between this lib and react-router.
### Steps to Reproduce

I can write a failing test when we have tests. :)

**Comment by jmurzy** [comment]
Sorry about this. I know what's going on here. Will submit a patch soon. 

🍺

**Comment by jonathanglasmeyer** [comment]
That's good to hear!👍🏻

**Comment by jmurzy** [comment]
This should fix it. Let me know if you run into any issues.

**Comment by jonathanglasmeyer** [comment]
Will check monday! Awesome. :)
