### ISSUE TITLE
A Route with `indexRoute` should not have a mandatory `component`

### ISSUE THREAD

**Issue by jonathanglasmeyer** [jmurzy/react-router-native#20]
In our web project with React Router we use the following route config for our route `/orders`:

``` js
// ordersRoute.js

export default {
  path: 'orders',
  onEnter: ListController.onEnter,
  indexRoute: {
    component: ListController,
  },
  childRoutes: [
    {
      path: ':orderId',
      indexRoute: {
        component: SingleController,
      },
      childRoutes: [
        images,
        chat,
      ],
    },
  ],
};
```

`/orders`/ renders `ListController`, `/orders/:orderId` renders `SingleController`.
This pattern does not work when using this lib, failing with  'Failed propTypes: Required prop `component` was not specified in `RouteView`.' and rendering nothing. 
I'd expect this library to match react router's behaviour of just rendering the indexRoute. Otherwise i'm forced to write it as follows:

``` js
// ordersRoute.native.js

const Wrapper = (props) => <View style={{flex: 1}}>{props.children}</View>;

export default <Route
  path='orders'
  component={Wrapper}
  onEnter={ListController.onEnter}>
  <IndexRoute component={ListController} />

  <Route path=':orderId' component={Wrapper} />
</Route>;
```

Where `Wrapper` just adds boilerplate. 

Is this complaint reasonable? Or was our web route config "bad" to begin with? RR [IndexRoutes documentation](https://github.com/reactjs/react-router/blob/master/docs/guides/IndexRoutes.md) also supplies `component` _plus_ an `indexRoute` component, which makes me thing we have it wrong anyways. _But_ why would it work then without supplying a `component`?

**Comment by jmurzy** [comment]
This should work as expected. #19 doesn't fix this? That was a good catch btw. 😅

**Comment by jonathanglasmeyer** [comment]
Well I'll double check tomorrow, but the proptype warning will be there for sure, which it shouldn't right?

**Comment by dchambers** [comment]
I think I just hit essentially the same issue. I was getting this error:

```
Failed propType: Required prop `component` was not specified in `RouteView`. Check the render method of `_class`.
```

which I fixed by changing my routes from something like this:

```
<StackRoute>
  <Route path="/" component={IndexPage}/>
  <Route path="/foo" component={FooPage}/>
</StackRoute>
```

to something like this:

```
<StackRoute component={View}>
  <Route path="/" component={IndexPage}/>
  <Route path="/foo" component={FooPage}/>
</StackRoute>
```

**Comment by jmurzy** [comment]
Ugh. Sorry, I think I misunderstood this when I replied ^. You cannot omit `component`. So the `propType` warning is correct. Nested components are passed in `children` prop to their parents. Without a wrapper component, it doesn't make sense to have an `IndexRoute`. I'd be surprised if this doesn't spit out errors on the web. 

🍺
