### ISSUE TITLE
How does it work with cyclic routes?

### ISSUE THREAD

**Issue by joonhocho** [jmurzy/react-router-native#24]
Think of typical social user relationships. 
A user can follow other users.

URL for John: `/user/john`
URL for Mike: `/user/mike`

URL change sequence:
`/user/john`
(push to)
`/user/john/followers`
(push to)
`/user/mike`
(push to)
`/user/mike/followers`
(push to)
`/user/john` (CYCLIC)
(pop back to)
`/user/mike/followers`
(pop back to)
`/user/mike`
(pop back to)
`/user/john/followers`
(pop back to)
`/user/john`

Is this scenario possible with current implementation?

**Comment by jmurzy** [comment]
Cyclic as in it should push a previously pushed `<Route>` to `<StackRoute>`? 

Totally. This should do it:

``` js
<StackRoute path="/user" component={...} >
  <Route path="/user/:username" component={...} overlayComponent={...} />
  <Route path="/user/:username/followers" component={...} overlayComponent={...} />
</StackRoute>
```

—or—

``` js
<StackRoute path="/user" component={...} >
  <Route path=":username" component={...} overlayComponent={...} />
  <Route path=":username/followers" component={...} overlayComponent={...} />
</StackRoute>
```

🍺

**Comment by joonhocho** [comment]
Awesome!
