### ISSUE TITLE
Why is the top-level `path` needed but ignored?

### ISSUE THREAD

**Issue by dchambers** [jmurzy/react-router-native#28]
In both the [usage example](https://github.com/jmurzy/react-router-native#usage) and the [code example](https://github.com/jmurzy/react-router-native/blob/master/examples/Aviato/app/routes.js) you have a top-level `TabsRoute` component having a path that doesn't appear to be part of the route, but is needed. In the code example I found that I could change the value to anything other than empty string and the code still worked.

What's going on here?

**Comment by jmurzy** [comment]
Sorry I know this can be a bit confusing. 

Navigating to a `<Route>` has the effect of pushing that route component as a scene to its containing `<TabsRoute>` or `<StackRoute>`.

`path` is required for both  `<TabsRoute>` and `<StackRoute>` to allow navigation to a previous state without pushing a new scene onto the navigation stack. This is especially useful when you have nested routes e.g. nested `<TabsRoute>`'s where you want to return to the inner `<TabsRoute>`'s last state without knowing what it is. So navigating to `/parentTab` will render its children in their previous states. Does this make sense?  

In both the example app and the README, we are using [absolute paths](https://github.com/reactjs/react-router/blob/master/docs/guides/RouteConfiguration.md#decoupling-the-ui-from-the-url). But there is nothing preventing you from using relative paths. It really depends on the semantics of your route configuration but they are essentially the same thing.

``` js
<StackRoute path="/user" component={...} >
  <Route path="/user/:username" component={...} overlayComponent={...} />
  <Route path="/user/:username/followers" component={...} overlayComponent={...} />
</StackRoute>
```

—or—

``` js
<StackRoute path="/user" component={...} >
  <Route path=":username" component={...} overlayComponent={...} />
  <Route path=":username/followers" component={...} overlayComponent={...} />
</StackRoute>
```

Also see #24 

🍺

**Comment by dchambers** [comment]
Hi @jmurzy, thanks for taking the time to provide an explanation here. I've read and re-read your comment, and played about with the code a lot since, but I'm still struggling to precisely grasp the operational differences between 'react-router' and 'react-router-native', and the reasons for those differences.

Would I be right in saying that 'react-router-native' works the same as 'react-router' provided the outer `path` is absolute and the inner path is relative, but works differently when:
1. The inner path is absolute, in which you case you can use different text to what you would with 'react-router', but you get the same result anyway?
2. The outer path is relative, in which case you get very different behaviour as the outer path does not form part of the route?

Regarding this statement:

> `path` is required for both `<TabsRoute>` and `<StackRoute>` to allow navigation to a previous state without pushing a new scene onto the navigation stack.

If a route unambiguously identifies the components to display, couldn't this be done by popping items off of the history object?

**Comment by dchambers** [comment]
Oh, maybe my misunderstanding also comes from the fact that I still haven't been able to do figure out what `component` and `overlayComponent` are for? I've tried playing playing about with these properties quite a bit, but am still yet to figure out how they're meant to be used.
