### ISSUE TITLE
Expose `cardStyle` prop on NavigationCard once it lands in a release

### ISSUE THREAD

**Issue by cpsubrian** [jmurzy/react-router-native#30]
Added via this PR https://github.com/facebook/react-native/pull/8471

Allows overriding things like the default card `backgroundColor`.

**Comment by jmurzy** [comment]
You should set the `backgroundColor` on the outmost `View` (wrapper) of your route `component`. 

That PR adds `cardStyle` prop to `NavigationCardStack` which we do not use in this lib. We use a lower level API called `NavigationTransitioner` and render `NavigationCard` directly. I agree, however, that we should change the `backgroundColor` of the NavigationCard from [this](https://github.com/jmurzy/react-router-native/blob/master/modules/styles.js#L20) to just `transparent`. Did you want to fix that in a PR?

🍺

**Comment by cpsubrian** [comment]
I absolutely can. Was looking through the source and didn't see the right stuff exposed but will look again. Its the color on NavigationCard that was bugging me.

**Comment by cpsubrian** [comment]
THis is closed by the PR that merged.
