### ISSUE TITLE
Missing dependencies.

### ISSUE THREAD

**Issue by twelvearrays** [jmurzy/react-router-native#32]
This project contains components that are currently under active development and considered experimental. If it is something you can debug and fix, please consider submitting a pull request instead!

---
### Version

| Dependency | Version |
| --- | --- |
| react-router-native | 2.0.0-alpha.2 |
| react-router | 3.0.0-alpha.1 |
| react-native | 0.30.0-rc.0 |
### Expected Behavior

To install with:

npm install --save react-router-native react-router
### Actual Behavior

Installed but I had to also install the follow modules in local directory:

fbjs
query-string
deep-equal

npm install --save fbjs query-string deep-equal

After installing these extra modules react-router-native is working as expected.

Thanks!

**Comment by cpsubrian** [comment]
@twelvearrays I wonder if you're using npm@2.x or npm@3.x?

**Comment by ronaldheft** [comment]
Same issue. npm@3.x. Peer dependencies need to be explicitly stated as they are not downloaded by default.

**Comment by jmurzy** [comment]
Not sure if this is a peer depencency issue.  **npm** can be flaky sometimes. Running `npm install` again does usually fix depencency issues.

Just pushed a new release, can you try again and let me know if it works for you?

``` sh
$ npm install --save react-router-native@v2.0.0-alpha.5 react-router@3.0.0-alpha.3
```

Thanks!

🍺

**Comment by sospedra** [comment]
Clean installation using the command:
` npm install --save react-router-native@v2.0.0-alpha.5 react-router@3.0.0-alpha.3`

Outputs:
```
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "react-router-native@v2.0.0-alpha.5" "react-router@3.0.0-alpha.3"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.3.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-router@3.0.0-alpha.3 wants react@^0.14.0 || ^15.0.0
npm ERR! peerinvalid Peer react-native@0.33.0-rc.0 wants react@15.3.1-rc.2

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ruben/labs/mobile-apps/npm-debug.log
```
