### ISSUE TITLE
Why is the default transition for StackRoute HORIZONTAL_PAGER?

### ISSUE THREAD

**Issue by jonathanglasmeyer** [jmurzy/react-router-native#43]
This tripped me up right now. I'd expect HORIZONTAL_CARD__STACK_, as the name implies. This also means that users of StackRoute won't get swipe back behaviour. Is this intended?

**Comment by jmurzy** [comment]
Animations in NavigationExperimental were slow and HORIZONTAL_PAGER used to perform much better than HORIZONTAL_CARD_STACK. A lot has changed since, so HORIZONTAL_CARD_STACK is a better default. Thanks! 

🍺
