### ISSUE TITLE
Requiring unknown module "history/lib/LocationUtils

### ISSUE THREAD

**Issue by gmchaturvedi1** [jmurzy/react-router-native#52]
Requiring unknown module "history/lib/LocationUtils

error is coming. Kindly suggest

Reagrds
GM

This project contains components that are currently under active development and considered experimental. If it is something you can debug and fix, please consider submitting a pull request instead!

---
### Version

| Dependency | Version |
| --- | --- |
| react-router-native |  |
| react-router |  |
| react-native | .33 |

**Comment by jonathanglasmeyer** [comment]
Could you specify steps to reproduce the error? Could you specify all dependency versions?

**Comment by gmchaturvedi1** [comment]
Its done after installing history package v 3.0 .I have one doubt can we
use this in production app

**Comment by jonathanglasmeyer** [comment]
Did you install the history version exactly as specified in `peerDependencies`?

**Comment by jonathanglasmeyer** [comment]
I'll close this for now. Please ping if you still need help. 🍻
