### ISSUE TITLE
Possible error with Redux

### ISSUE THREAD

**Issue by DenJohX** [jmurzy/react-router-native#53]
Hi, I'm having some issues with redux. 
### Version

| Dependency | Version |
| --- | --- |
| react-router-native | 2.0.0-alpha.5 |
| react-router | 3.0.0-alpha.3 |
| react-native | 0.34.0 |
### Problems

By the current example: 

``` Javascript
import React from 'react'
import { createStore, combineReducers, applyMiddleware } from 'redux'
import { Provider } from 'react-redux'
import { Router, nativeHistory } from 'react-router-native';
import { syncHistoryWithStore, routerReducer } from 'react-router-redux'

import reducers from '<project-path>/reducers'

// Add the reducer to your store on the `routing` key
const store = createStore(
  combineReducers({
    ...reducers,
    routing: routerReducer
  })
)

// Create an enhanced history that syncs navigation events with the store
const history = syncHistoryWithStore(nativeHistory, store)

const routes = (
  <Provider store={store}>
    /* Tell the Router to use our enhanced history */
    <Router history={nativeHistory}>
      /* ... */
    </Router>
  </Provider>
);

AppRegistry.registerComponent('YourApp', () => () => routes);
```

It seems to work, but extraneously the Hot Reloading stops working (tho I'm not sure if it is related), anyways, that doesn't seems to be the correct code, the router line should be:

``` Javascript
<Router history={history}>
```

Notice the use of the synced history instead of the native one, thats the correct usage, as copied from   react-router-redux README  

However, using it this way gives the error: 
**Cannot read property 'action' of undefined** 

from the line 115 in Router.js: 

``` Javascript
    if (nextLocation.action === HISTORY_POP) { 
```

please advice.

**Comment by DenJohX** [comment]
I made a repo with an example of the code I'm using, (with the problems I mentioned).

Please check it https://github.com/DenJohX/test-react-router-native

**Comment by berkedel** [comment]
That error is possibly due to the router does not know the current path at start.
Try to add this code `history.push('/')` after creating synchronized history like below:

``` js
import React from 'react'
import { createStore, combineReducers, applyMiddleware } from 'redux'
import { Provider } from 'react-redux'
import { Router, nativeHistory } from 'react-router-native';
import { syncHistoryWithStore, routerReducer } from 'react-router-redux'

import reducers from '<project-path>/reducers'

// Add the reducer to your store on the `routing` key
const store = createStore(
  combineReducers({
    ...reducers,
    routing: routerReducer
  })
)

// Create an enhanced history that syncs navigation events with the store
const history = syncHistoryWithStore(nativeHistory, store)
// Set current path to '/'
history.push('/')

const routes = (
  <Provider store={store}>
    /* Tell the Router to use our enhanced history */
    <Router history={history}>
      /* ... */
    </Router>
  </Provider>
);

AppRegistry.registerComponent('YourApp', () => () => routes);
```

**Comment by DenJohX** [comment]
@berkedel  yup, that was it.

The problem with the hot reloading persists, but the router is now working with the correct history.

Thanks
