### ISSUE TITLE
question to router

### ISSUE THREAD

**Issue by Eightyplus** [jmurzy/react-router-native#62]
where are the available functions on the router? Documentation?

How do I clear history? pop all?

**Comment by Eightyplus** [comment]
/history/lib/Actions.js?
push/replace/pop?

**Comment by jonathanglasmeyer** [comment]
The documentation for the `router` can be found in the react-router repository itself. One straight forward example of using the router api directly can be found in `modules/Go`.

**Comment by Eightyplus** [comment]
That answer does not really satisfy my question, but I guess that just is what it is.
