### ISSUE TITLE
comparison with react-native-router-flux

### ISSUE THREAD

**Issue by ms88privat** [jmurzy/react-router-native#7]
This router looks nice!

Could you please provide some information about the differences compared to [react-native-router-flux](https://github.com/aksonov/react-native-router-flux)? Because router-flux is about the most used router until now I would say.

Is it only the API / Interface or does it have some other advantages or disadvantages?

From what I can tell:
- makes deep linking possible
- ???

EDIT: Also how do you see the status of this project? Is it production ready (because of 1.0 version)? Maybe you could specify a Roadmap with features that are about to come? 

Thanks for working on this 👍

**Comment by jmurzy** [comment]
Thanks for the question. 

Don't let npm confuse you. This project is currently under active development—aka use in production at your own risk. There used to be another project with the same name that the previous owner nuked. Unfortunately, removing or re-publishing old versions is no longer supported by npm. So the packages that are currently available on npm are the artifacts of a different project, and the first version of this library will probably be released as _v2.0.0_ and strictly follow [React Versioning Scheme](https://facebook.github.io/react/blog/2016/02/19/new-versioning-scheme.html) afterwards.

I'm not familiar with [react-native-router-flux](https://github.com/aksonov/react-native-router-flux) so I cannot tell you what the differences are. There's an [example app](https://github.com/jmurzy/react-router-native/tree/master/examples/Aviato) in the repo if you want to compare the two and share your findings with the community. That'd be awesome. 👍 

This project currently has two primary goals:
- Introduce URL-driven-development (UDD) to native apps
- Keep API as close to [react-router](https://github.com/reactjs/react-router) as makes sense

I admit the native app ecosystem is not web-like, and you can argue that URLs aren't necessary and most people don't care—or so I thought, until I started doing UDD in my native projects. Often people tend to take URLs for granted and advantages are not so pronounced, and as you've already discovered, deep-linking is one of those perks. 

Also, choosing the right abstraction makes you focus on the real challenges and lets you forget the insignificant details. I think [react-router](https://github.com/reactjs/react-router) has done a pretty good job of it.

🍺

**Comment by jonathanglasmeyer** [comment]
@jmurzy, do you have an opinion on the reasons the react-router maintainers stated for not supporting react native? I'm specifically thinking about the argument that native navigation patterns don't map to the web / URL paradigm (for example iOS tabs that have _one navigation stack each_).
We don't want to "force" web navigation patterns onto our native apps behaviour, it's more important that they feel intuitive from a platform best practices point of view. This is basically the only concern we have in adopting this library.

Also, the amount of breaking changes for NavigationExperimental has been kind of crazy recently; kudos for keeping up with that. I currently postponed the routing question for a little while, hoping that the pace of change will settle down soon.

**Comment by jmurzy** [comment]
@jonathanewerner Take a look at this [discussion](https://github.com/reactjs/react-router/issues/743) for background. So basically, it's decided that a reducer-based paradigm was better suited to native navigation, and this is exactly what this library does—marries the react-router concepts to those of NavigationExperimental. Ultimately, it is also the [direction](https://github.com/reactjs/react-router/issues/3190) react-router wants to take, and I think we can influence that discussion going forward.

You can use this library to do anything and everything NavigationExperimental can do. You can do nested tabs and stacks easily, and if you want `<Link>` to respond differently for a given route, [the new reducer API](https://github.com/jmurzy/react-router-native/commit/0f5187d92c9c7b30944b4b87ad48f0c582325986) gives you fine-grained control over the interaction. It's something I added over the weekend, so it's still new.

🍺

**Comment by jonathanglasmeyer** [comment]
K awesome, I knew the first discussion, not the second though. I'll try digging through the code on Friday and maybe work on documentation. 👍🏻

**Comment by jmurzy** [comment]
@jonathanewerner You're awesome! 💯 👍 

🍺

**Comment by jmurzy** [comment]
Closing this based upon the discussion above. Please, feel free to reopen this if you want to follow up.

🍺
