### ISSUE TITLE
`invariant` missing stack trace

### ISSUE THREAD

**Issue by jonathanglasmeyer** [jmurzy/react-router-native#9]
I wonder if it's possible to get stack traces for errors thrown via `invariant`.

![image](https://cloud.githubusercontent.com/assets/3755413/15857900/15604a5e-2cbe-11e6-829d-2dc4954a34fa.png)

I had to grep the source to see whats going on.

**Comment by jmurzy** [comment]
Can you reproduce this? We should probably throw a better error message here, especially for cases where we know the exact cause e.g. misconfiguration of routes. Otherwise, this shouldn't really be thrown unless an incompatible version of react-router is installed.

🍺

**Comment by jonathanglasmeyer** [comment]
Yea it occurred when I tried specifying the routes as plain JavaScript objects and forget to add a `reducer` prop. I first thought i should amend the error message to say that this prop is necessary but wasn't sure if that's correct in all cases (i.e. IndexRoute does not need a routeType, so i was not sure if every route would need a reducer)
